name: Deploy Mobile App

on:
  push:
    branches: [main]
    paths:
      - 'apps/mobile/**'
      - 'packages/**'
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - android
          - ios
      profile:
        description: 'Build profile'
        required: true
        default: 'preview'
        type: choice
        options:
          - development
          - preview
          - production

env:
  NODE_VERSION: '18.17.0'
  PNPM_VERSION: '9.0.0'

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    if: github.event.inputs.platform == 'android' || github.event.inputs.platform == 'all'
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Setup environment
        run: |
          cp apps/mobile/.env.${{ github.event.inputs.profile || 'preview' }} apps/mobile/.env
      
      - name: Build Android app
        working-directory: apps/mobile
        run: |
          eas build --platform android --profile ${{ github.event.inputs.profile || 'preview' }} --non-interactive
      
      - name: Submit to Play Store
        if: github.event.inputs.profile == 'production'
        working-directory: apps/mobile
        run: |
          eas submit --platform android --profile production --non-interactive

  build-ios:
    name: Build iOS
    runs-on: macos-latest
    if: github.event.inputs.platform == 'ios' || github.event.inputs.platform == 'all'
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Setup environment
        run: |
          cp apps/mobile/.env.${{ github.event.inputs.profile || 'preview' }} apps/mobile/.env
      
      - name: Build iOS app
        working-directory: apps/mobile
        run: |
          eas build --platform ios --profile ${{ github.event.inputs.profile || 'preview' }} --non-interactive
      
      - name: Submit to App Store
        if: github.event.inputs.profile == 'production'
        working-directory: apps/mobile
        run: |
          eas submit --platform ios --profile production --non-interactive